services:
  - type: web
    name: n8n-schedule
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: n8n-schedule-db
          property: connectionString

databases:
  - name: n8n-schedule-db
    databaseName: reminders
    user: reminders_user
